server:
  port: 8888
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:3000/eureka/
  instance:
    instance-id: user
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 10 # eureka客户端需要多长时间发送心跳给eureka服务器
    lease-expiration-duration-in-seconds: 30 # Eureka在接收到示例的最后一次发出的心跳后，需要等待多长时间

spring:
  application:
    name: client-user # 此实例注册到eureka服务器的name

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        requestVolumeThreshold: 5
        sleepWindowInMilliseconds: 5000