server:
  port: 8002

spring:
  application:
    name: cloud-payment-service

eureka:
  client:
    # 表示是否将自己注册进EurekaServer，默认为true
    register-with-eureka: true
    # 是否从EurekaServer抓取配置信息，默认为true，集群必须设置，才能配合Ribbon负载均衡
    fetch-registry: true
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7001.com:7001/eureka

  instance:
    instance-id: payment8002
    prefer-ip-address: true